MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    NAME: "build_deeplab_backbone"
  SEM_SEG_HEAD:
    NAME: "SMPSemSegHead"
    NUM_CLASSES: 4
    IGNORE_VALUE: 0
DATALOADER:
  NUM_WORKERS: 0
INPUT:
  MIN_SIZE_TRAIN: (256, 512)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 768
  MIN_SIZE_TRAIN_SAMPLING: choice
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 90000
OUTPUT_DIR: './output_deeplab'
