MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    NAME: "build_unet_backbone"
  SEM_SEG_HEAD:
    NAME: "SMPSemSegHead"
    NUM_CLASSES: 4
    IGNORE_VALUE: 0
DATALOADER:
  NUM_WORKERS: 0
INPUT:
  MIN_SIZE_TRAIN: (256, 384)
  MAX_SIZE_TRAIN: 384
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 384
  MIN_SIZE_TRAIN_SAMPLING: range
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 90000
OUTPUT_DIR: './output_unet'
